name: SilverSkillz
main: us.teaminceptus.silverskillz.SilverSkillz
version: 1.0.1
api-version: 1.17
description: Edit your minecraft experience in new and exciting ways with over 15 skills!
commands:
  skills:
    usage: /skills
    description: Opens a GUI with skills
    permission: silverskillz.command.skill
    aliases: [skill, sks, sk, skll, sklls]
  addprogress:
    usage: /addprogress <player> <amount> [skill]
    description: Add progress for each skill or one skill
    permission: silverskillz.command.addprogress
    aliases: [addp, aprogress, addprog]
  resetprogress:
    usage: /resetprogress <player> [skill]
    description: Reset progress for a skill
    permission: silverskillz.command.resetprogress
    aliases: [resetp, rprogress, resetprog, rstprogress]
  settings:
    usage: /settings
    permission: silverskillz.command.settings
    description: Open the settings menu
    aliases: [stngs, sett, playersettings]
  removeprogress:
    usage: /removeprogress <player> <amount> [skill]
    description: Remove progress for each skill or one skill
    permission: silverskillz.command.removeprogress
    aliases: [removep, rprogress, lessprogress, lessprog, removeprog, rprog]
  skreload:
    usage: /skreload
    description: Reload Configurations
    permission: silverskillz.command.skreload
    aliases: [ssreload, silverreloadm skr, ssr]
  
permissions:
  silverskillz.*:
    default: op
    description: Access to all SilverSkillz Permissions
    children:
      silverskillz.command: true
  # Commands
  silverskillz.command:
    default: op
    description: Access to all SilverSkillz commands
    children:
      silverskillz.command.skill: true
      silverskillz.command.addprogress: true
      silverskillz.command.resetprogress: true
      silverskillz.command.settings: true
      silverskillz.command.removeprogress: true
      silverskillz.command.skreload: true
      silverskillz.user: true
  silverskillz.command.skill:
    default: op
    description: Access to /skill command
  silverskillz.command.addprogress:
    default: op
    description: Access to /addprogress
  silverskillz.command.resetprogress:
    default: op
    description: Access to /resetprogress
  silverskillz.command.settings:
    default: true
    description: Access to player's personal settings (/settings or /playersettings)
  silverskilz.command.removeprogress:
    default: op
    description: Access to /removeprogress or /lessprogress
  silverskillz.command.skreload:
    default: op
    description: Access to /skreload, which reloads configs
  # User Commands
  silverskillz.user.abilities:
    description: Access to list available abilities unlocked through leveling up skills
    default: true

    